version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - /path/to/root:/srv
      - /path/database.db:/database.db
      - /path/settings.json:/.filebrowser.json
    # ports:
    #  - HOST:80
    networks:
      - npm-net

networks:
  npm-net:
    external: true
