version: "3"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 443:443
      # Disable 81 after proxy configured
      - 81:81
    environment:
      DISABLE_IPV6: "true"
    extra_hosts:
      - "HOSTNAME:TARGET"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm-net

# docker network create npm-net
networks:
  npm-net:
    external: true

# Defaults
# Email:    admin@example.com
# Password: changeme
