version: "3"

services:
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-persist:/var/lib/redis
    # ports:
    #  - HOST_PORT:6379
    networks:
      - npm-net

volumes:
  redis-persist:

# Use nginx proxy manager
networks:
  npm-net:
    external: true
